const types = {
  SET_CUSTOMER: "@shop/SET_CUSTOMER",
  REQUEST_PETSHOPS: "@shop/REQUEST_PETSHOPS",
  SET_PETSHOPS: "@shop/SET_PETSHOPS",
  SET_PETSHOP_MAP_SELECTED: "@shop/SET_PETSHOP_MAP_SELECTED",
  SET_MAP_CENTER: "@shop/SET_MAP_CENTER",
  REQUEST_PETSHOP: "@shop/REQUEST_PETSHOP",
  SET_PETSHOP: "@shop/SET_PETSHOP",
  TOGGLE_CART_PRODUCT: "@shop/TOGGLE_CART_PRODUCT",
  SET_TRANSACTION: "@shop/SET_TRANSACTION",
  MAKE_PURCHASE: "@shop/MAKE_PURCHASE",
};

export default types;
